// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using MonoTouch.Foundation;

namespace SuperKoikoukesse.iOS
{
	public partial class HighScoresControlViewController : UIViewController
	{
		public HighScoresControlViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
