// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace SuperKoikoukesse.iOS
{
	public partial class PXNTimerLabel : UILabel
	{
		public PXNTimerLabel (IntPtr handle) : base (handle)
		{
		}
	}
}
