// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace SuperKoikoukesse.iOS
{
	public partial class VersusMatchsCollectionViewCell : UICollectionViewCell
	{
		public VersusMatchsCollectionViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
