source "https://rubygems.org"

gem "sinatra"
gem "haml"
gem "data_mapper"

group :development do
  gem "sqlite3"
  gem "dm-sqlite-adapter"
  gem "shotgun"
  gem "tux"
end

group :production do
    gem "pg"
    gem "dm-postgres-adapter"
end
