source "https://rubygems.org"

gem "sinatra"
gem "sqlite3"
gem "haml"
gem "data_mapper"
gem "dm-sqlite-adapter"

group :development do
  gem "shotgun"
  gem "tux"
end

group :production do
  gem 'thin'
end
