# Procfile is the heroku entry point for each process
web: bundle exec thin -R config.ru start -p $PORT
#web: bundle exec thin -R config.ru start -p $PORT -e $RACK_ENV
#web: bundle exec ruby web.rb -p $PORT
